package erpsolams.erpsolamsmodel.erpsolamseo;

import erpsolglob.erpsolglobmodel.erpsolglobclasses.ERPSolGlobalsEntityImpl;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.Date;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Mar 04 15:00:19 PKT 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SysUsersImpl extends ERPSolGlobalsEntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Companyid,
        Userid,
        Password,
        Locationid,
        Empid,
        FullName,
        Modifiedby,
        Storeid,
        ModifiedDate,
        Createdby,
        CreationDate,
        ActiveStatus,
        Regionid,
        PAllow,
        FAllow,
        FisAllow,
        PasswordChk,
        AuditorCheck,
        Reggrpid,
        UserCategory,
        LoginMb,
        EbsUserid,
        UserType,
        Userseq,
        SysUsersDetail,
        SysUserCustomer;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int COMPANYID = AttributesEnum.Companyid.index();
    public static final int USERID = AttributesEnum.Userid.index();
    public static final int PASSWORD = AttributesEnum.Password.index();
    public static final int LOCATIONID = AttributesEnum.Locationid.index();
    public static final int EMPID = AttributesEnum.Empid.index();
    public static final int FULLNAME = AttributesEnum.FullName.index();
    public static final int MODIFIEDBY = AttributesEnum.Modifiedby.index();
    public static final int STOREID = AttributesEnum.Storeid.index();
    public static final int MODIFIEDDATE = AttributesEnum.ModifiedDate.index();
    public static final int CREATEDBY = AttributesEnum.Createdby.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int ACTIVESTATUS = AttributesEnum.ActiveStatus.index();
    public static final int REGIONID = AttributesEnum.Regionid.index();
    public static final int PALLOW = AttributesEnum.PAllow.index();
    public static final int FALLOW = AttributesEnum.FAllow.index();
    public static final int FISALLOW = AttributesEnum.FisAllow.index();
    public static final int PASSWORDCHK = AttributesEnum.PasswordChk.index();
    public static final int AUDITORCHECK = AttributesEnum.AuditorCheck.index();
    public static final int REGGRPID = AttributesEnum.Reggrpid.index();
    public static final int USERCATEGORY = AttributesEnum.UserCategory.index();
    public static final int LOGINMB = AttributesEnum.LoginMb.index();
    public static final int EBSUSERID = AttributesEnum.EbsUserid.index();
    public static final int USERTYPE = AttributesEnum.UserType.index();
    public static final int USERSEQ = AttributesEnum.Userseq.index();
    public static final int SYSUSERSDETAIL = AttributesEnum.SysUsersDetail.index();
    public static final int SYSUSERCUSTOMER = AttributesEnum.SysUserCustomer.index();

    /**
     * This is the default constructor (do not remove).
     */
    public SysUsersImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("erpsolams.erpsolamsmodel.erpsolamseo.SysUsers");
    }


    /**
     * Gets the attribute value for Companyid, using the alias name Companyid.
     * @return the value of Companyid
     */
    public String getCompanyid() {
        return (String) getAttributeInternal(COMPANYID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Companyid.
     * @param value value to set the Companyid
     */
    public void setCompanyid(String value) {
        setAttributeInternal(COMPANYID, value);
    }

    /**
     * Gets the attribute value for Userid, using the alias name Userid.
     * @return the value of Userid
     */
    public String getUserid() {
        return (String) getAttributeInternal(USERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Userid.
     * @param value value to set the Userid
     */
    public void setUserid(String value) {
        setAttributeInternal(USERID, value);
    }

    /**
     * Gets the attribute value for Password, using the alias name Password.
     * @return the value of Password
     */
    public String getPassword() {
        return (String) getAttributeInternal(PASSWORD);
    }

    /**
     * Sets <code>value</code> as the attribute value for Password.
     * @param value value to set the Password
     */
    public void setPassword(String value) {
        setAttributeInternal(PASSWORD, value);
    }

    /**
     * Gets the attribute value for Locationid, using the alias name Locationid.
     * @return the value of Locationid
     */
    public String getLocationid() {
        return (String) getAttributeInternal(LOCATIONID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Locationid.
     * @param value value to set the Locationid
     */
    public void setLocationid(String value) {
        setAttributeInternal(LOCATIONID, value);
    }

    /**
     * Gets the attribute value for Empid, using the alias name Empid.
     * @return the value of Empid
     */
    public String getEmpid() {
        return (String) getAttributeInternal(EMPID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Empid.
     * @param value value to set the Empid
     */
    public void setEmpid(String value) {
        setAttributeInternal(EMPID, value);
    }

    /**
     * Gets the attribute value for FullName, using the alias name FullName.
     * @return the value of FullName
     */
    public String getFullName() {
        return (String) getAttributeInternal(FULLNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for FullName.
     * @param value value to set the FullName
     */
    public void setFullName(String value) {
        setAttributeInternal(FULLNAME, value);
    }

    /**
     * Gets the attribute value for Modifiedby, using the alias name Modifiedby.
     * @return the value of Modifiedby
     */
    public String getModifiedby() {
        return (String) getAttributeInternal(MODIFIEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Modifiedby.
     * @param value value to set the Modifiedby
     */
    public void setModifiedby(String value) {
        setAttributeInternal(MODIFIEDBY, value);
    }

    /**
     * Gets the attribute value for Storeid, using the alias name Storeid.
     * @return the value of Storeid
     */
    public String getStoreid() {
        return (String) getAttributeInternal(STOREID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Storeid.
     * @param value value to set the Storeid
     */
    public void setStoreid(String value) {
        setAttributeInternal(STOREID, value);
    }

    /**
     * Gets the attribute value for ModifiedDate, using the alias name ModifiedDate.
     * @return the value of ModifiedDate
     */
    public Date getModifiedDate() {
        return (Date) getAttributeInternal(MODIFIEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ModifiedDate.
     * @param value value to set the ModifiedDate
     */
    public void setModifiedDate(Date value) {
        setAttributeInternal(MODIFIEDDATE, value);
    }

    /**
     * Gets the attribute value for Createdby, using the alias name Createdby.
     * @return the value of Createdby
     */
    public String getCreatedby() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Createdby.
     * @param value value to set the Createdby
     */
    public void setCreatedby(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the value of CreationDate
     */
    public Date getCreationDate() {
        return (Date) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreationDate.
     * @param value value to set the CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for ActiveStatus, using the alias name ActiveStatus.
     * @return the value of ActiveStatus
     */
    public String getActiveStatus() {
        return (String) getAttributeInternal(ACTIVESTATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for ActiveStatus.
     * @param value value to set the ActiveStatus
     */
    public void setActiveStatus(String value) {
        setAttributeInternal(ACTIVESTATUS, value);
    }

    /**
     * Gets the attribute value for Regionid, using the alias name Regionid.
     * @return the value of Regionid
     */
    public String getRegionid() {
        return (String) getAttributeInternal(REGIONID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Regionid.
     * @param value value to set the Regionid
     */
    public void setRegionid(String value) {
        setAttributeInternal(REGIONID, value);
    }

    /**
     * Gets the attribute value for PAllow, using the alias name PAllow.
     * @return the value of PAllow
     */
    public String getPAllow() {
        return (String) getAttributeInternal(PALLOW);
    }

    /**
     * Sets <code>value</code> as the attribute value for PAllow.
     * @param value value to set the PAllow
     */
    public void setPAllow(String value) {
        setAttributeInternal(PALLOW, value);
    }

    /**
     * Gets the attribute value for FAllow, using the alias name FAllow.
     * @return the value of FAllow
     */
    public String getFAllow() {
        return (String) getAttributeInternal(FALLOW);
    }

    /**
     * Sets <code>value</code> as the attribute value for FAllow.
     * @param value value to set the FAllow
     */
    public void setFAllow(String value) {
        setAttributeInternal(FALLOW, value);
    }

    /**
     * Gets the attribute value for FisAllow, using the alias name FisAllow.
     * @return the value of FisAllow
     */
    public String getFisAllow() {
        return (String) getAttributeInternal(FISALLOW);
    }

    /**
     * Sets <code>value</code> as the attribute value for FisAllow.
     * @param value value to set the FisAllow
     */
    public void setFisAllow(String value) {
        setAttributeInternal(FISALLOW, value);
    }

    /**
     * Gets the attribute value for PasswordChk, using the alias name PasswordChk.
     * @return the value of PasswordChk
     */
    public String getPasswordChk() {
        return (String) getAttributeInternal(PASSWORDCHK);
    }

    /**
     * Sets <code>value</code> as the attribute value for PasswordChk.
     * @param value value to set the PasswordChk
     */
    public void setPasswordChk(String value) {
        setAttributeInternal(PASSWORDCHK, value);
    }

    /**
     * Gets the attribute value for AuditorCheck, using the alias name AuditorCheck.
     * @return the value of AuditorCheck
     */
    public String getAuditorCheck() {
        return (String) getAttributeInternal(AUDITORCHECK);
    }

    /**
     * Sets <code>value</code> as the attribute value for AuditorCheck.
     * @param value value to set the AuditorCheck
     */
    public void setAuditorCheck(String value) {
        setAttributeInternal(AUDITORCHECK, value);
    }

    /**
     * Gets the attribute value for Reggrpid, using the alias name Reggrpid.
     * @return the value of Reggrpid
     */
    public String getReggrpid() {
        return (String) getAttributeInternal(REGGRPID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Reggrpid.
     * @param value value to set the Reggrpid
     */
    public void setReggrpid(String value) {
        setAttributeInternal(REGGRPID, value);
    }

    /**
     * Gets the attribute value for UserCategory, using the alias name UserCategory.
     * @return the value of UserCategory
     */
    public String getUserCategory() {
        return (String) getAttributeInternal(USERCATEGORY);
    }

    /**
     * Sets <code>value</code> as the attribute value for UserCategory.
     * @param value value to set the UserCategory
     */
    public void setUserCategory(String value) {
        setAttributeInternal(USERCATEGORY, value);
    }

    /**
     * Gets the attribute value for LoginMb, using the alias name LoginMb.
     * @return the value of LoginMb
     */
    public String getLoginMb() {
        return (String) getAttributeInternal(LOGINMB);
    }

    /**
     * Sets <code>value</code> as the attribute value for LoginMb.
     * @param value value to set the LoginMb
     */
    public void setLoginMb(String value) {
        setAttributeInternal(LOGINMB, value);
    }

    /**
     * Gets the attribute value for EbsUserid, using the alias name EbsUserid.
     * @return the value of EbsUserid
     */
    public String getEbsUserid() {
        return (String) getAttributeInternal(EBSUSERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for EbsUserid.
     * @param value value to set the EbsUserid
     */
    public void setEbsUserid(String value) {
        setAttributeInternal(EBSUSERID, value);
    }

    /**
     * Gets the attribute value for UserType, using the alias name UserType.
     * @return the value of UserType
     */
    public String getUserType() {
        return (String) getAttributeInternal(USERTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for UserType.
     * @param value value to set the UserType
     */
    public void setUserType(String value) {
        setAttributeInternal(USERTYPE, value);
    }

    /**
     * Gets the attribute value for Userseq, using the alias name Userseq.
     * @return the value of Userseq
     */
    public Integer getUserseq() {
        return (Integer) getAttributeInternal(USERSEQ);
    }

    /**
     * Sets <code>value</code> as the attribute value for Userseq.
     * @param value value to set the Userseq
     */
    public void setUserseq(Integer value) {
        setAttributeInternal(USERSEQ, value);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getSysUsersDetail() {
        return (RowIterator) getAttributeInternal(SYSUSERSDETAIL);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getSysUserCustomer() {
        return (RowIterator) getAttributeInternal(SYSUSERCUSTOMER);
    }


    /**
     * @param userseq key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Integer userseq) {
        return new Key(new Object[] { userseq });
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        setERPSolPKSeqName("SYS_USERS_SEQ");
        setERPSolPKColumnName("Userseq");
        
        super.create(attributeList);
    }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        super.doDML(operation, e);
    }
}

